const path = require("path");
const express = require("express");
const session = require("express-session");
const cookieParser = require("cookie-parser");
const dotenv = require("dotenv");
const {
	pagebuilderThemes,
	blockHideOrShowWithSchedule,
} = require("./helperFile");

if (process.env.NODE_ENV !== "development") {
	dotenv.config({ path: "./config.env" });
}

const app = express();

app.set("view engine", "ejs");
app.set("views", "resources/views");

app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

app.use(express.static(path.join(__dirname, "public")));

app.use(
	session({
		key: "user_id",
		secret: "keyboard cat",
		resave: false,
		saveUninitialized: true,
		cookie: { secure: false },
	})
);

//~ ////////////////////////////////////////////////////
//~ ROUTES
//~ ////////////////////////////////////////////////////

// app.use((req, res, next) => {
// 	console.log({ sesssion: req.session, cookie: req.cookies });
// 	if (req.session && req.session.user && req.cookies.user_id) {
// 		res.render("dashboard", { name: req.session.user.username });
// 		return next();
// 	}
// 	else {

// 	}
// });

app.get("/", (req, res) => {
	res.render("page-builder", {
		pageTitle: "Page Builder",
		path: "/page-builder",
		user: null,
		content_age_limit: 1,
		page_builder_id: 1234,
		pagebuilderThemes,
		blockHideOrShowWithSchedule,
		og_tags: null,
		favicon: null,
		site_title: "Dummy project",
		is_publish: true,
		branding: 1,
		facebook_pixel_tracking_id: "123",
		google_analytics_tracking_id: "UA-183639594-1",
		is_theme: false,
		is_font_family: null,
		is_background: false,
		theme_selected: null,
		is_publish: false,
		is_theme: false,
		is_font_family: null,
		is_background: false,
		button_style: {
			background: null,
			fontColor: null,
			class: "fillrounded",
		},
		opacity: 20,
		tracking_list: [
			{
				position: "Head",
				type: "Google Analytics",
				snippet_code: "UA-183639594-1",
			},
			{
				position: "Head",
				type: "Facebook Pixel",
				snippet_code: "123",
			},
		],
		button_style: {
			background: null,
			fontColor: null,
			class: "fillrounded",
		},
		profile: {
			position: 1,
			profile_pic:
				"https://linkjoy-dev.s3.ap-south-1.amazonaws.com/developement/publicpagebuilder/284c741e05d-7c39-499e-b092-1359321cdc42",
			module_type: "profile",
			layout_type: 2,
			is_hidden: false,
			is_scheduled: false,
			scheduled_start_date: null,
			scheduled_end_date: null,
			module_data: {
				brand_title:
					'<p class="ql-align-center" style="background-color:transparent!important"><strong style="color:rgb(92, 0, 0); background-color:transparent!important">#WeAreRare <span class="ql-cursor" style="background-color:transparent!important">\ufeff</span></strong></p> ',
				button_title: null,
				button_url: null,
			},
		},
		// pagebuilder_data: [
		// 	{
		// 		id: 0,
		// 		position: 1,
		// 		module_type: "subtitle_text",
		// 		name: "Subtitle & Text",
		// 		title: '<p style="background-color:transparent!important" class="ql-align-center"><strong style="color:rgb(92, 0, 0); background-color:transparent!important">“Being&nbsp;rare&nbsp;is about being comfortable with yourself.</strong></p><p style="background-color:transparent!important" class="ql-align-center"><strong style="color:rgb(92, 0, 0); background-color:transparent!important"> I’ve stopped trying to be perfect.</strong></p><p class="ql-align-center" style="background-color:transparent!important"><strong style="color:rgb(92, 0, 0); background-color:transparent!important"> I just want to be me.”</strong></p><p style="background-color:transparent!important" class="ql-align-center"><span style="color:rgb(92, 0, 0); background-color:transparent!important">💋</span></p><p class="ql-align-center" style="background-color:transparent!important"><strong style="color:rgb(92, 0, 0); background-color:transparent!important">SELENA GOMEZ</strong></p><p style="background-color:transparent!important"><br></p> ',
		// 		icon: "button-and-text-outline",
		// 		layout_type: null,
		// 		is_hidden: false,
		// 		is_scheduled: false,
		// 		scheduled_start_date: null,
		// 		scheduled_end_date: {
		// 			start: "3:31 PM",
		// 			end: "3:36 PM",
		// 			timezone: "Asia/Calcutta",
		// 		},
		// 		module_data: {
		// 			text: null,
		// 			subtitle:
		// 				'<p style="background-color:transparent!important" class="ql-align-center"><strong style="color:rgb(92, 0, 0); background-color:transparent!important">“Being&nbsp;rare&nbsp;is about being comfortable with yourself.</strong></p><p style="background-color:transparent!important" class="ql-align-center"><strong style="color:rgb(92, 0, 0); background-color:transparent!important"> I’ve stopped trying to be perfect.</strong></p><p class="ql-align-center" style="background-color:transparent!important"><strong style="color:rgb(92, 0, 0); background-color:transparent!important"> I just want to be me.”</strong></p><p style="background-color:transparent!important" class="ql-align-center"><span style="color:rgb(92, 0, 0); background-color:transparent!important">💋</span></p><p class="ql-align-center" style="background-color:transparent!important"><strong style="color:rgb(92, 0, 0); background-color:transparent!important">SELENA GOMEZ</strong></p><p style="background-color:transparent!important"><br></p> ',
		// 		},
		// 	},
		// 	{
		// 		id: 7,
		// 		position: 1,
		// 		module_type: "delimiter",
		// 		title: null,
		// 		name: "Delimiter",
		// 		icon: "code-slash-outline",
		// 		layout_type: "13",
		// 		is_hidden: false,
		// 		is_scheduled: false,
		// 		scheduled_start_date: null,
		// 		scheduled_end_date: {
		// 			start: "3:51 PM",
		// 			end: "3:56 PM",
		// 			timezone: "Asia/Calcutta",
		// 		},
		// 		module_data: {
		// 			is_type: false,
		// 			is_color: "#7F2649",
		// 			is_width: false,
		// 			is_edge: false,
		// 		},
		// 	},
		// 	{
		// 		id: 8,
		// 		position: 1,
		// 		module_type: "video_player",
		// 		title: '<p style="background-color:transparent!important"><strong style="background-color:transparent!important; color:rgb(127, 38, 73)">Rare Beauty is breaking down unrealistic standards of perfection. </strong></p><p style="background-color:transparent!important"><br></p><p style="background-color:transparent!important"><br></p>',
		// 		name: "Video",
		// 		icon: "you-tube-videos-outline",
		// 		is_hidden: false,
		// 		is_scheduled: false,
		// 		scheduled_start_date: null,
		// 		scheduled_end_date: {
		// 			start: "3:26 PM",
		// 			end: "3:31 PM",
		// 			timezone: "Asia/Calcutta",
		// 		},
		// 		module_data: {
		// 			title: '<p style="background-color:transparent!important"><strong style="background-color:transparent!important; color:rgb(127, 38, 73)">Rare Beauty is breaking down unrealistic standards of perfection. </strong></p><p style="background-color:transparent!important"><br></p><p style="background-color:transparent!important"><br></p>',
		// 			url: "https://www.youtube.com/watch?v=8vec_b2Bs2I",
		// 			embeddedUrl: "https://www.youtube.com/embed/8vec_b2Bs2I",
		// 			type: "youTube",
		// 			poster: null,
		// 			width: 100,
		// 			height: 315,
		// 			controls: false,
		// 			autoplay: false,
		// 		},
		// 	},
		// 	{
		// 		id: 6,
		// 		position: 5,
		// 		module_type: "social_links",
		// 		name: "Social Links",
		// 		icon: "social-links-outline",
		// 		title: null,
		// 		layout_type: 1,
		// 		is_hidden: false,
		// 		is_scheduled: false,
		// 		scheduled_start_date: null,
		// 		scheduled_end_date: {
		// 			start: "3:26 PM",
		// 			end: "3:31 PM",
		// 			timezone: "Asia/Calcutta",
		// 		},
		// 		module_data: {
		// 			0: {
		// 				name: "Instagram",
		// 				type: "instagram",
		// 				placeholder: "Instagram username",
		// 				link: "rarebeauty",
		// 				icon: "instagram-outline",
		// 			},
		// 			1: {
		// 				type: "facebook",
		// 				name: "Facebook",
		// 				placeholder: "Facebook username or page id",
		// 				link: "https://www.facebook.com/Rare-Beauty-102403614660064/?modal=admin_todo_tour",
		// 				icon: "facebook-outline",
		// 			},
		// 			2: {
		// 				name: "Twitter",
		// 				type: "twitter",
		// 				placeholder: "Twitter username",
		// 				link: "rarebeauty",
		// 				icon: "twitter-outline",
		// 			},
		// 			3: {
		// 				name: "Youtube",
		// 				type: "youtube",
		// 				placeholder: "Youtube channel url",
		// 				link: "https://www.youtube.com/channel/UCvOtsjwO04Seaep0J2clYEw",
		// 				icon: "youtube-outline",
		// 			},
		// 			4: {
		// 				name: "Linkedin",
		// 				type: "linkedin",
		// 				placeholder: "LinkedIn profile url",
		// 				link: null,
		// 				icon: "linkedin-outline",
		// 			},
		// 			5: {
		// 				name: "Pinterest",
		// 				type: "pinterest",
		// 				placeholder: "Pinterest username",
		// 				link: null,
		// 				icon: "pinterest-outline",
		// 			},
		// 			6: {
		// 				name: "Tumblr",
		// 				type: "tumblr",
		// 				placeholder: "Tumblr username",
		// 				link: null,
		// 				icon: "tumblr-outline",
		// 			},
		// 			7: {
		// 				name: "Patreon",
		// 				type: "patreon",
		// 				placeholder: "Patreon username",
		// 				link: null,
		// 				icon: "patreon-outline",
		// 			},
		// 			8: {
		// 				name: "VK",
		// 				type: "vk",
		// 				placeholder: "VK username or page id",
		// 				link: null,
		// 				icon: "vk-outline",
		// 			},
		// 			9: {
		// 				name: "Snapchat",
		// 				type: "snapchat",
		// 				placeholder: "Snapchat username",
		// 				link: null,
		// 				icon: "snapchat-outline",
		// 			},
		// 			10: {
		// 				name: "Telegram",
		// 				type: "telegram",
		// 				link: null,
		// 				icon: "telegram-outline",
		// 				placeholder: "Telegram username",
		// 			},
		// 			11: {
		// 				name: "Github",
		// 				type: "github",
		// 				placeholder: "Github username",
		// 				link: null,
		// 				icon: "github-outline",
		// 			},
		// 			12: {
		// 				name: "Whatsapp",
		// 				type: "whatsapp",
		// 				placeholder: "+1 6072068989",
		// 				textPlaceholder:
		// 					"Predefined text: e.g Give me further information about...",
		// 				link: null,
		// 				text: null,
		// 				icon: "whatsapp-outline",
		// 			},
		// 		},
		// 	},
		// ],
		pagebuilder: [
			{
				id: 0,
				position: 1,
				module_type: "subtitle_text",
				name: "Subtitle & Text",
				title: null,
				icon: "button-and-text-outline",
				layout_type: null,
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: {
					text: null,
					subtitle: null,
				},
			},
			{
				id: 1,
				position: 1,
				module_type: "button_text",
				name: "Button & Text",
				title: null,
				btn_pic: null,
				layout_type: 1,
				icon: "button-and-text-outline",
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				size: "w-80",
				module_data: {
					button_title: null,
					button_link: null,
				},
				animate: null,
			},
			{
				id: 2,
				position: 1,
				module_type: "delimiter",
				title: null,
				name: "Delimiter",
				icon: "code-slash-outline",
				layout_type: 1,
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: {
					is_type: false,
					is_color: null,
					is_width: false,
					is_edge: false,
				},
			},
			{
				id: 3,
				position: false,
				module_type: "image-carousel",
				title: null,
				name: "Image Carousel",
				icon: "images-outline",
				layout_type: 1,
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				slide_title: null,
				slide_transition: 2,
				height: 300,
				border_radius: 0,
				module_data: [],
			},
			{
				id: 4,
				position: 1,
				module_type: "video_player",
				title: null,
				name: "Video",
				icon: "you-tube-videos-outline",
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				background_color: "#979797",
				module_data: {
					title: null,
					url: null,
					embeddedUrl: null,
					type: null,
					poster: null,
					width: 100,
					height: 315,
					controls: false,
					autoplay: false,
				},
				animate: null,
			},
			{
				id: 5,
				position: 1,
				module_type: "instagram_feed",
				title: null,
				name: "Instagram Feed",
				icon: "instagram-feed-outline",
				layout_type: 2,
				insta_feed_load: [],
				insta_arr: [],
				is_hidden: false,
				is_scheduled: false,
				color: "#000",
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: {
					title: "<p>Instagram</p>",
					user_name: null,
				},
				is_instagram_biolink: false,
			},
			{
				id: 6,
				position: 1,
				module_type: "youtube_video",
				title: null,
				name: "Youtube Video",
				icon: "you-tube-videos-outline",
				layout_type: 1,
				youtube_feed_load: [],
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: {
					title: null,
					url: null,
				},
				animate: null,
			},
			{
				id: 7,
				position: 1,
				module_type: "medium_feed",
				title: null,
				name: "Medium Feed",
				icon: "medium-blog-outline",
				layout_type: 1,
				medium_feed_load: [],
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: {
					title: null,
					user_name: null,
				},
				animate: null,
			},
			{
				id: 8,
				position: 1,
				module_type: "dynamic_feed",
				title: null,
				name: "Dynamic Feed",
				icon: "medium-blog-outline",
				layout_type: 1,
				dynamic_feed_load: [],
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: {
					title: null,
					url: null,
				},
			},
			{
				id: 9,
				position: 1,
				module_type: "i_frame",
				name: "IFrame",
				title: null,
				icon: "code-working-outline",
				layout_type: null,
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				size: "w-80",
				module_data: {
					iframe_link: null,
					width: 100,
					height: 400,
				},
			},
			{
				id: 10,
				position: 1,
				module_type: "messengers_block",
				name: "Get In Touch",
				icon: "chatbox-double",
				title: null,
				layout_type: 1,
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: [
					{
						name: "Whatsapp",
						type: "whatsapp",
						placeholder: "+1 6072068989",
						textPlaceholder:
							"Predefined text: e.g Give me further information about...",
						link: null,
						text: null,
						icon: "logo-whatsapp",
						formIcon: "whatsapp-outline",
					},
					{
						type: "messenger",
						name: "Messenger",
						placeholder: "Messenger/Facebook username",
						link: null,
						icon: "logo-messenger",
						formIcon: "messenger-outline",
					},
					{
						name: "Telegram",
						type: "telegram",
						link: null,
						icon: "logo-telegram",
						formIcon: "telegram-outline",
						placeholder: "Telegram username",
					},
					{
						name: "Skype",
						type: "skype",
						link: null,
						icon: "logo-skype",
						formIcon: "skype-outline",
						placeholder: "Skype username",
					},
					{
						name: "Mail",
						type: "mail",
						placeholder: "Email address",
						textPlaceholder: "Subject:",
						link: null,
						text: null,
						icon: "email",
						formIcon: "email",
					},
					{
						name: "Phone Number",
						type: "phone",
						link: null,
						icon: "call",
						formIcon: "telephone-outline",
						placeholder: "+1 999 999 9999",
					},
					{
						name: "Viber",
						type: "viber",
						link: null,
						icon: "logo-viber",
						formIcon: "viber-outline",
						placeholder: "Viber number",
					},
					{
						name: "Discord",
						type: "discord",
						link: null,
						icon: "logo-discord",
						formIcon: "discord-outline",
						placeholder: "Discord Link",
					},
				],
				animate: null,
			},
			{
				id: 11,
				position: 1,
				module_type: "email_sms_list",
				title: null,
				name: "Subscribe",
				icon: "mail-outline",
				layout_type: 1,
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				is_enable: true,
				background_color: "#979797",
				animate: null,
				module_data: {
					destination_active: "zapier",
					destination: [
						{
							name: "destination",
							title: "Zapier",
							active: 1,
							value: "zapier",
						},
					],
					name_arr: {
						name: "full_name",
						active: 1,
						title: "Name field",
						placeholder: "Full name",
						value: "Full name",
						required: true,
						type: "text",
						col: 4,
					},
					email_arr: {
						name: "email",
						active: 1,
						title: "Email",
						placeholder: "Email",
						required: true,
						type: "email",
						value: null,
						col: 4,
					},
					mobile_no_arr: {
						name: "mobile_no",
						active: 0,
						title: "Mobile No.",
						placeholder: "Mobile No.",
						required: true,
						value: null,
						type: "number",
						col: 4,
					},
					style: 2,
					title: "<p>Join mailing list</p>",
					submit_button: "<p>Subscribe</p>",
					description: "<p>dsdsdsd</p>",
					success_message: "Thank you for subscribing!",
					fields: [
						{
							name: "custom_field",
							active: 0,
							title: "Custom field",
							placeholder: "Name of custom field",
							value: null,
							required: true,
							type: "text",
							col: 4,
						},
					],
					custom_legal_info: {
						active: 0,
						title: "Custom legal info",
						fields: {
							legal_text: {
								name: "legal_text",
								active: 0,
								title: "Legal text",
								placeholder: "Legal text",
								value: null,
								required: false,
								type: "text",
								col: 4,
							},
							legal_url: {
								name: "legal_url",
								active: 0,
								title: "Legal URL",
								placeholder: "Legal URL",
								value: null,
								required: false,
								type: "text",
								col: 4,
							},
						},
					},
				},
			},
			{
				id: 12,
				position: 1,
				module_type: "support",
				title: null,
				name: "Get paid",
				icon: "cash-outline",
				layout_type: 1,
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				is_enable: false,
				background_color: "#979797",
				module_data: {
					button: {
						name: "button_text",
						active: 1,
						title: "Button Text",
						placeholder: "Tap here to support me",
						value: "<p>Tap here to support me</p>",
						required: true,
						type: "text",
						col: 4,
					},
					heading: {
						name: "heading",
						active: 1,
						title: "Heading",
						placeholder: "Get Paid For",
						value: "<p>Get Paid For</p>",
						required: true,
						type: "text",
						col: 4,
					},
					buy_desc: {
						name: "buy_desc",
						active: 1,
						title: "Tagline",
						placeholder: "coffee ☕",
						required: true,
						type: "text",
						value: "<p>coffee ☕</p>",
						col: 4,
					},
					unit_price: {
						name: "unit_price",
						active: 1,
						title: "Unit Price",
						placeholder: "$ 3",
						required: true,
						value: null,
						type: "number",
						col: 4,
					},
					support_desc: {
						name: "support_desc",
						active: 1,
						title: "Description",
						placeholder: "Description",
						required: true,
						type: "text",
						value: null,
						col: 4,
					},
					support_success_url: {
						name: "support_success_url",
						active: 1,
						title: "Payment Success URL",
						placeholder: "https://www.linkjoy.io/",
						required: false,
						type: "text",
						value: null,
						col: 4,
					},
					payment_mode: null,
					payment_type: null,
				},
			},
			{
				id: 13,
				position: 1,
				module_type: "button-text-group",
				title: null,
				name: "Button Group",
				icon: "buttons-outline",
				layout_type: 1,
				no_of_columns: 2,
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: [],
			},
			{
				id: 14,
				position: 1,
				module_type: "social_links",
				name: "Social Links",
				icon: "social-links-outline",
				title: null,
				layout_type: 1,
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				animate: null,
				module_data: [
					{
						type: "facebook",
						name: "Facebook",
						placeholder: "Facebook username or page id",
						link: null,
						icon: "facebook-outline",
					},
					{
						name: "Instagram",
						type: "instagram",
						placeholder: "Instagram username",
						link: null,
						icon: "instagram-outline",
					},
					{
						name: "Twitter",
						type: "twitter",
						placeholder: "Twitter username",
						link: null,
						icon: "twitter-outline",
					},
					{
						name: "Youtube",
						type: "youtube",
						placeholder: "Youtube channel url",
						link: null,
						icon: "youtube-outline",
					},
					{
						name: "Linkedin",
						type: "linkedin",
						placeholder: "LinkedIn profile url",
						link: null,
						icon: "linkedin-outline",
					},
					{
						name: "Pinterest",
						type: "pinterest",
						placeholder: "Pinterest username",
						link: null,
						icon: "pinterest-outline",
					},
					{
						name: "Tumblr",
						type: "tumblr",
						placeholder: "Tumblr username",
						link: null,
						icon: "tumblr-outline",
					},
					{
						name: "Patreon",
						type: "patreon",
						placeholder: "Patreon username",
						link: null,
						icon: "patreon-outline",
					},
					{
						name: "VK",
						type: "vk",
						placeholder: "VK username or page id",
						link: null,
						icon: "vk-outline",
					},
					{
						name: "Snapchat",
						type: "snapchat",
						placeholder: "Snapchat username",
						link: null,
						icon: "snapchat-outline",
					},
					{
						name: "Telegram",
						type: "telegram",
						link: null,
						icon: "telegram-outline",
						placeholder: "Telegram username",
					},
					{
						name: "Github",
						type: "github",
						placeholder: "Github username",
						link: null,
						icon: "github-outline",
					},
					{
						name: "Whatsapp",
						type: "whatsapp",
						placeholder: "+1 6072068989",
						textPlaceholder:
							"Predefined text: e.g Give me further information about...",
						link: null,
						text: null,
						icon: "whatsapp-outline",
					},
					{
						name: "TikTok",
						type: "tiktok",
						placeholder: "TikTok username",
						link: null,
						icon: "tiktok-outline",
					},
					{
						name: "Twitch.tv",
						type: "twitch",
						placeholder: "Twitch.tv username",
						link: null,
						icon: "twitch-outline",
					},
				],
			},
			{
				id: 15,
				position: 1,
				module_type: "add_to_contacts",
				name: "Add to Contacts",
				icon: "add-to-contacts",
				title: "Just adding some Contacts",
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: {
					title: "The title",
					first_name: "Jaimin",
					last_name: "Rathwa",
					email: [
						{
							type: "gmail",
							address: "temp@gmail.com",
						},
					],
					phone: [
						{
							type: "mobile",
							number: "+9112345678",
						},
					],
					organization: "momentum",
					position: "Intern",
					address: {
						street: "Abc / 124 street",
						city: "New york",
						state: "New york",
						country: "USA",
						zip: "123455",
					},
					availability: 12,
					font_color: "#323232",
					add_to_contacts_cta: "<p>Add to Contacts</p>",
				},
				animate: null,
			},
			{
				id: 16,
				position: 1,
				module_type: "html_block",
				title: null,
				name: "HTML Code",
				icon: "logo-html5",
				is_hidden: false,
				is_scheduled: false,
				scheduled_start_date: null,
				scheduled_end_date: {
					start: "11:55 am",
					end: "0:00 pm",
					timezone: "Asia/Calcutta",
				},
				module_data: {
					content: null,
				},
				animate: null,
			},
		],
	});
});

app.listen(5000, () => {
	console.log("App is running at port 5000");
});
